### ISSUE TITLE
register package?

### ISSUE THREAD

**Issue by simonbyrne** [stevengj/BibTeX.jl#6]
Would it be possible to register this package?

Also, I noticed that the CI isn't hooked up. I'd be happy to help out if you can give me access.

**Comment by lucianolorenti** [comment]
It would be great if the package is registered!

**Comment by Azzaare** [comment]
Bump

As this parser is better than the one I used in Bibliography.jl, I would like to import it. I would rather do with an official rep, is it possible?

EDIT: I am actually testing the code within BibParser.jl (the parser dependencyof Bibliography.jl). It works pretty good. If you don't want to maintain/register this parser I can fork it or integrate it within BibParser.jl (also MIT expat). Please let me know!
On the long term, I would like to have a parser working similarly as Tokenize.jl, but I don't have time for it now!

**Comment by stevengj** [comment]
@dpsanders, I think we need someone with admin permissions here to add @simonbyrne as a collaborator…

**Comment by dpsanders** [comment]
I don't seem to have admin permissions. cc @tawheeler

**Comment by tawheeler** [comment]
Cool - added @dpsanders and @stevengj as admins. Wasn't sure what level to add @simonbyrne at - please add him with what you think is appropriate.

**Comment by dpsanders** [comment]
Thanks @tawheeler!

**Comment by Azzaare** [comment]
I have integrated (by copy paste ...) the current state of BibTeX.jl, it works perfectly within Bibliography.jl
I will be happy to properly import it once officially register.

I will probably have some PR to do eventually too

If you're curious about it, you can see the results of using BibTeX.jl within Bibliography.jl on my website : [http://baffier.fr/publications.html](http://baffier.fr/publications.html)

**Comment by Azzaare** [comment]
As I don't have answer so far, I will add a reference to this project within BibParser.jl and will improve the parser directly from there.

**Comment by simonbyrne** [comment]
@dpsanders can you register this (or give me access)?

**Comment by stevengj** [comment]
I think @tawheeler needs to add @simonbyrne

**Comment by tawheeler** [comment]
Added @simonbyrne as a Bibtex.jl admin

**Comment by simonbyrne** [comment]
Awaiting automerge: https://github.com/JuliaRegistries/General/pull/19730
