### ISSUE TITLE
parse_bibtex on examples.bib output an empty Dict

### ISSUE THREAD

**Issue by Azzaare** [stevengj/BibTeX.jl#8]
When I try to parse the example file from the repository, parse_bibtex output a tuple with an empty string and an empty dict.

FYI, I am using Julia 4.2 on windows.

**Comment by tlienart** [comment]
you have to do `parse_bibtex(read(path_to_file, String))` and not `parse_bibtex(path_to_file)`

**Comment by Azzaare** [comment]
Thanks! I will try it today.
